### ISSUE TITLE
Make RestCallErrorCode implement Exception

### ISSUE THREAD

**Issue by degustaf** [discord-haskell/discord-haskell#130]
This will allow easy logging of rest errors by throwing the returned error.

**Comment by degustaf** [comment]
Probably worth mentioning that this appears to be a very simple change, and I am more than willing to do it. I just want to make sure that the maintainers are onboard.

**Comment by aquarial** [comment]
Intriguing, I'm not sure how this works. Would this be an internal thing? Right now restCall has monad type of `DiscordHandler (Either RestCallErrorCode a)` so the edge of the API is pattern matching on the Either.

Are you looking for an internal change or an external change?

One way to process the result is to pattern match like:

```haskell
example = do
    Right result <- restCall Something  -- throws exception if Left RestCall. 
    print result
```

**Comment by degustaf** [comment]
Yeah, it shouldn't change how any of the existing code works. But it would allow
```
example = do
  result <- restCall Something
  case result of
    Left e -> throw e
    Right res -> print res
```
This would propogate the error up to the try in `runDiscordLoop`

**Comment by degustaf** [comment]
Internally, the change should be as simple as `instance Exception RestCallErrorCode` in src/Discord.hs

I could implement it my use of the package, but then GHC throws an Orphan Instance Warning.

**Comment by aquarial** [comment]
oo Yeah that looks good. A PR would work great!
