### ISSUE TITLE
Cache does not contain guilds

### ISSUE THREAD

**Issue by tam-carre** [discord-haskell/discord-haskell#157]
### Problem

When printing the Cache's `cacheGuilds` field, `fromList []` is printed.

### Expected behavior

The cache contains the guilds that the bot is in.

Reference code suggested by @L0neGamer on Discord: https://github.com/discord-haskell/discord-haskell/blob/d101c886cb502180f859411218254ed38dd07081/src/Discord/Internal/Gateway/Cache.hs#L58

Minimal example:

```hs
{-# LANGUAGE OverloadedStrings #-}

module Main (main) where

import Discord
import Discord.Types
import qualified Data.Text.IO as TIO
import UnliftIO (liftIO)

main :: IO ()
main = do
  err <- runDiscord $ def
    { discordToken   = "some token"
    , discordOnEvent = onEvent
    }
  liftIO $ TIO.putStrLn err

onEvent :: Event -> DiscordHandler ()
onEvent (Ready {}) = do
  cache <- readCache
  liftIO . TIO.putStrLn . (<>) "Cache: ". show . cacheGuilds $ cache

onEvent _ = pure ()
```

**Comment by L0neGamer** [comment]
Ah, I see the issue here. The cache is only populated after Ready is received, using GuildCreate events. They should arrive soon after Ready is received. I will make some adjustments to the Cache to make it strict, but that shouldn't change anything here.

**Comment by tam-carre** [comment]
@L0neGamer 

> They should arrive soon after Ready is received.

My tests seem to say no

```hs
onReady :: ApplicationId -> DiscordHandler ()
onReady appId = do
  cache <- readCache
  echo $ "Cache: " <> show (cacheGuilds cache)
  void . forkIO $ do
    sleep 20
    echo $ "Cache after 20 seconds: " <> show (cacheGuilds cache)
```

```
Cache: fromList []
Cache after 20 seconds: fromList []
```

![1666784060](https://user-images.githubusercontent.com/1331748/198015999-b1709b5b-f52b-4ad3-b045-e792da64e7b8.png)

**Comment by tam-carre** [comment]
WAIT!

**Comment by tam-carre** [comment]
> Ah, I see the issue here. The cache is only populated after Ready is received, using GuildCreate events. They should arrive soon after Ready is received. I will make some adjustments to the Cache to make it strict, but that shouldn't change anything here.

Ignore deleted messages.
```onReady :: ApplicationId -> DiscordHandler ()
onReady appId = do
  checkCache
  void . forkIO $ do
    sleep 5
    checkCache
  where
  checkCache :: DiscordHandler ()
  checkCache = do
    cache <- readCache
    echo $ "Cache: " <> show (cacheGuilds cache)
```

Confirmed cache is populated soon after receiving the `Ready` event.
