### ISSUE TITLE
Library Parse Exception on ModifyGuildRole

### ISSUE THREAD

**Issue by chuahou** [discord-haskell/discord-haskell#167]
On current master (8a82208cbb59e1ab24176a90de8b0706c08ddb31), there appears to be a parse error when making a `ModifyGuildRole` call, which seems to be from parsing the returned result into `Role`.

```
restCall $ ModifyGuildRole guildId roleId $ ModifyGuildRoleOpts
    { modifyGuildRoleOptsName = Just "test_123"
    , modifyGuildRoleOptsPermissions = Nothing
    , modifyGuildRoleOptsColor = Nothing
    , modifyGuildRoleOptsMentionable = Nothing
    , modifyGuildRoleOptsSeparateSidebar = Nothing
    }
```
results in
```
Left (RestCallErrorCode 400 "Library Parse Exception"
"restcall - parse exception
[Error in $.permissions: parsing Integer failed, expected Number, but encountered String]
while handling
\"{\\\"id\\\": \\\"<role ID>\\\", \\\"name\\\": \\\"test_123\\\", \\\"description\\\": null,
\\\"permissions\\\": \\\"0\\\", \\\"position\\\": 1, \\\"color\\\": 0, \\\"hoist\\\": false,
\\\"managed\\\": false, \\\"mentionable\\\": false, \\\"icon\\\": null, \\\"unicode_emoji\\\": null,
\\\"flags\\\": 0}\"")
```
which I suspect is due to the change of role permissions from `Text` to `RolePermissions` in #164. Trying the same before #164 was merged (adf1b3bdeabd6a300c315410695c8c7cbb041327) seems to perform correctly with
```
Right (Role {roleId = <role ID>, roleName = "test_123", roleColor = DiscordColorRGB 0 0 0,
    roleHoist = False, rolePos = 1, rolePerms = "0", roleManaged = False, roleMention = False})
```

---

I believe this is likely due to [the new implementation expecting an `Integer` when parsing the JSON response](https://github.com/XanderDJ/discord-haskell/blob/217c89ab1cd51324cc295b6af0536a4cc402f682/src/Discord/Internal/Types/Prelude.hs#L116-L126) despite [Discord's role object having it as a string](https://discord.com/developers/docs/topics/permissions#role-object). Perhaps the `FromJSON` instance should be modified to parse the string before parsing the contents as an `Integer`? I'm not familiar enough with the Discord API to know if role permissions are represented as strings everywhere.

**Comment by L0neGamer** [comment]
I think you've correctly identified the issue; if you wish to, a pr changing that instance should be sufficient.

**Comment by chuahou** [comment]
Sure, I'll put it in in a bit. Thanks!
