### ISSUE TITLE
[Discussion] Stack support

### ISSUE THREAD

**Issue by Annwan** [discord-haskell/discord-haskell#177]
Creating a separate thread to discuss the questions about stack support raised in #176 

## Previous comments

> Unrelated but a future issue: I noticed that while Cabal CI works fine across versions, the Stack CI build check always uses 8.10.7 across all of the build matrix - so it's kind of useless. This is because it uses the stack.yaml file which specifies the stackage snapshot which ties the GHC version.
>
> To solve this we need to create different stack.yaml files for each GHC version we support, using a different snapshot for each. Then pass that to CI with a --stack-yaml flag.
>
> Alternatively, my subjective opinion but Stack seems to be falling out of use in favour of directly using cabal, so perhaps we can cut that out of CI entirely and focus on cabal.

_Originally posted by @yutotakano in https://github.com/discord-haskell/discord-haskell/issues/176#issuecomment-1642580138_

> (I'm not sure what my opinion counts for here, as I mostly just lurk in the Haskell community!) Stack usage has been consistently dropping over time, this is reflected in the annual Haskell survey results — compare, say, [2022](https://taylor.fausak.me/2022/11/18/haskell-survey-results/#s3q0) with [2019](https://taylor.fausak.me/2019/11/16/haskell-survey-results/#s3). But at the same time, it seems that there's still a significant proportion of people using Stack (49% in 2022). Given this, and since Stack support doesn't seem too difficult to do correctly, I'd be open to picking it up in a separate PR 🙂

_Originally posted by @penelopeysm in https://github.com/discord-haskell/discord-haskell/issues/176#issuecomment-1642815557_

>Re: stack automation, I'm happy for us to move in either direction, but the current position isn't good. I think reducing the stack stuff we have to support would be nice.

_Originally posted by @L0neGamer in https://github.com/discord-haskell/discord-haskell/issues/176#issuecomment-1642881615_

**Comment by Annwan** [comment]
I myself mostly agree with @L0neGamer point of view, with the added note that even if we don't use stack for the lib in here, it would still work for stack user like any other hackage package

**Comment by yutotakano** [comment]
New idea: we can have Cabal build tests on all supported versions, and just a single stack.yaml file build test. This would need occasional bumping of the LTS but essentially does what it's doing now with less confusion.

Just feeling unsure about removing stack CI altogether in #180, feels like stack.yaml would get neglected easily.

**Comment by L0neGamer** [comment]
Do you want to make this adjustment or should I look into it?

**Comment by yutotakano** [comment]
> Do you want to make this adjustment or should I look into it?

Sorry for the delay, I've just submitted PR #183 for it.
