### ISSUE TITLE
Update emoji list

### ISSUE THREAD

**Issue by penelopeysm** [discord-haskell/discord-haskell#178]
Currently `discord-haskell` uses the `emoji` package ([Hackage](https://hackage.haskell.org/package/emoji), [GitHub](https://github.com/nakaji-dayo/hs-emoji)) to convert strings like `:eyes:` (or just `eyes`) into its Unicode representation  👀.

But `emoji` hasn't been updated for a while, and consequently some of the newer emojis aren't supported — for example, `:orange_heart:` 🧡 fails. As a workaround, you can just use `\x1F9E1`, but it'd be nice to be able to use the names.

One easy solution would be to use the `emojis` package instead ([Hackage](https://hackage.haskell.org/package/emojis), [GitHub](https://github.com/jgm/emojis)). This isn't *fully* up-to-date either (it doesn't have Emoji 15.0), but it does contain all the emojis that Discord supports (which is up to Emoji 14.0).

Happy to put in a PR if that seems sensible!

**Comment by L0neGamer** [comment]
This seems sensible and would be appreciated!
