### ISSUE TITLE
Improve error messages of unfilled cache

### ISSUE THREAD

**Issue by L0neGamer** [discord-haskell/discord-haskell#186]
In #185 it was unclear what exactly was wrong with using the cache without knowledge of library internals. 

We should improve the cache by using a tvar to ensure it's always filled, and initially filling it with an error that says "cache is either disabled, or is accessed before the Ready event has been received".

Alternative methods that don't use error would be appreciated, but as this is a value that once set should stay set I think I prefer this implementation.

An alternative could be a custom type and cache accessor that throws an exception in the usual way when the cache is not available.

**Comment by aquarial** [comment]
Can this issue be closed? 

PR #190 means the cache won't be empty outside of crashes.]

TVar vs MVar is an interesting question. I like the MVar situation because the invariants are simple for internal code and a user has to go out of their way to take the cache out of the MVar.
