### ISSUE TITLE
How do I access the ModalData in an InteractionModalSubmit event?

### ISSUE THREAD

**Issue by tankorsmash** [discord-haskell/discord-haskell#193]
I've been enjoying using this library quite a bit, and it's been straightforward to use, which is nice.

This may be a silly question, but I'm trying to handle the data the user has entered into their interaction modal, but the type `Types.Interaction.ModalData` appears to be hidden. I'm going off the [latest docs](https://hackage.haskell.org/package/discord-haskell-1.15.6/docs/Discord-Internal-Types-Interactions.html#t:Interaction), (but I happen to be using 1.14). I think the type would be purple if it was exposed, but I'm not certain.

![image](https://github.com/discord-haskell/discord-haskell/assets/1312390/9adb51dd-2881-4c48-b179-1fa974e20a71)

Sample code where I'd like to be able to read the custom ID from the ModalData

```hs
    onDiscordEvent ( InteractionCreate ( InteractionModalSubmit _ _ myModalData _ _ _ _ _ _ _)) =
       -- print the custom ID from myModalData here
```

It doesn't seem like I can pattern match on it to get the fields out, since the [type](https://hackage.haskell.org/package/discord-haskell-1.14.0/docs/src/Discord.Internal.Types.Interactions.html#ModalData) isn't exposed, and I don't see a way to call any functions on it.

```
 Not in scope: data constructor ‘ModalData’
    Perhaps you meant variable ‘modalData’ (imported from Discord.Interactions)
```

There's probably something I'm missing, but I can't quite figure out how to get the custom ID or the components from the `ModalData`.

**Comment by aquarial** [comment]
Looks like you found a minor issue with the library, where we don't export the `ModalData` ADT internals.

**Comment by tankorsmash** [comment]
Oh cool! I'm new to Haskell, so I wasn't sure if there's some pattern I didn't know about. Thanks for solving this so quickly!

**Comment by aquarial** [comment]
The 1.16 version (just released) now exports `ModalData`

**Comment by tankorsmash** [comment]
Awesome thank you!
