### ISSUE TITLE
Storing states between handler invocations

### ISSUE THREAD

**Issue by illuminator3** [discord-haskell/discord-haskell#81]
Let's say I have an event handler:
```hs
eventHandler :: Event -> DiscordHandler ()
eventHandler event = case event of
    MessageCreate m -> let author = messageAuthor m in {- store the author in a list -}
    _ -> pure ()
```
How would I save data, so that it persists between event handler invocations?

**Comment by aquarial** [comment]
Good q, I should make an example documenting this. For now reference [issue #42](https://github.com/aquarial/discord-haskell/issues/42), but change the IORef to MVar [(quick tutorial on mvar)](https://riptutorial.com/haskell/example/15506/communicating-between-threads-with--mvar-)

IORef is safe in single threaded contexts, but in multithreaded (like the event handler), we need to use threadsafe stuff.

```haskell
                        , discordForkThreadForEvents = False
                        -- Optional, but lets us use IORef instead of a
                        -- concurrency handler like MVar.
```

Leave this issue open until there's an example in the `./examples/` showing an MVar.

**Comment by illuminator3** [comment]
Thanks.

**Comment by aquarial** [comment]
Here's an example for state https://github.com/aquarial/discord-haskell/blob/master/examples/state-counter.hs

I'm not happy with how finnicky the `IO ()` vs `DiscordHandler ()` monad transformer stuff is, but this works for now.

**Comment by aquarial** [comment]
Fixed with examples/state-counter.
